dist: trusty
language: node_js
node_js: stable

script: yarn test:ci

jobs:
  include:
    - stage: npm release
      node_js: stable
      before_deploy:
      - yarn install
      - yarn build:ci
      deploy:
        skip_cleanup: true
        provider: npm
        email: "webdev@experium.ru"
        api_key: $NPM_API_KEY
        on:
          branch: master
